{
  "name": "Release",
  "on": {
    "release": {
      "types": [
        "published"
      ]
    }
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "permissions": {
        "id-token": "write"
      },
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Install uv",
          "uses": "astral-sh/setup-uv@v5",
          "with": {
            "version": "0.6.0"
          }
        },
        {
          "name": "Install dependencies",
          "run": "uv sync --dev"
        },
        {
          "name": "Tests",
          "run": "uv run --group dev pytest"
        },
        {
          "name": "Integration tests",
          "run": "uv run --group dev pytest --nbval-lax --nbval-current-env Example.ipynb tests/Test*.ipynb"
        },
        {
          "name": "Build package",
          "run": "uv build"
        },
        {
          "name": "Publish package distributions to PyPI",
          "uses": "pypa/gh-action-pypi-publish@release/v1"
        }
      ]
    }
  }
}
