{
  "name": "Test",
  "on": {
    "workflow_dispatch": {},
    "pull_request": {}
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Install uv",
          "uses": "astral-sh/setup-uv@v5",
          "with": {
            "version": "0.6.0"
          }
        },
        {
          "name": "Install dependencies",
          "run": "uv sync --group dev"
        },
        {
          "name": "Check format",
          "run": "uv run --group dev ruff format --check ."
        },
        {
          "name": "Check lints",
          "run": "uv run --group dev ruff check ."
        },
        {
          "name": "Tests",
          "run": "uv run --group dev pytest"
        },
        {
          "name": "Integration tests",
          "run": "uv run --group dev pytest --nbval-lax --nbval-current-env Example.ipynb tests/Test*.ipynb"
        },
        {
          "name": "Build package",
          "run": "uv build"
        },
      ]
    }
  }
}
